---
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.5.8
  - 2.6.6
  - 2.7.1
before_install: gem install bundler
gemfile:
  - Gemfile
  - gemfiles/rails52.gemfile
  - gemfiles/rails6.gemfile

# jobs:
#   exclude:
