---
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.4.9
  - 2.5.7
  - 2.6.5
before_install: gem install bundler
gemfile:
  - Gemfile
  - gemfiles/rails42.gemfile
  - gemfiles/rails51.gemfile
  - gemfiles/rails52.gemfile
  - gemfiles/rails6.gemfile
