---
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6.1
before_install: gem install bundler -v 2.0.1
gemfile:
  - Gemfile
  - gemfiles/rails42.gemfile
  - gemfiles/rails51.gemfile
  - gemfiles/rails52.gemfile
